### ISSUE TITLE
[Request] Handling of folders

### ISSUE THREAD

**Issue by Pudhmasta** [wavebeem/yantp#1]
Hey, 

Love the extension, very simple and easy. 
I'd like to ask if there was a better way to display bookmarks inside folders. Perhaps having just the folder name display and when clicked it drops down and shows you the bookmarks inside. 

Other than that great job!

Thanks, 
Pudhmasta

**Comment by wavebeem** [comment]
It already shows bookmarks in folders as far as I know. Can you show me a screenshot of the problem?

**Comment by wavebeem** [comment]
Closing this as it seems to already be fixed and OP never responded.
